---

- name: deploy docker containers
  become: yes
  hosts: servers
  roles:
    - role: geerlingguy.docker
  vars_files:
    - secrets/secrets.yaml

  tasks:
    - name: pull docker images
      community.docker.docker_login:
        registry_url: "docker.io"
        username: "bapdecha"
        password: "{{ docker_token }}"
    - name: run docker front containers
      community.docker.docker_container:
        name: my-app-front
        image: bapdecha/baprep:front
        ports:
          - 80:4173
        state: started
        recreate: true
        restart_policy: always
    - name: run docker back containers
      community.docker.docker_container:
        name: my-app-back
        image: bapdecha/baprep:back
        ports:
          - 8080:8080
        state: started
        recreate: true
        restart_policy: always